In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# Dimesnsions and shape of an array
arr.ndim

1

In [ ]:
arr = np.array(90)
arr.ndim

0

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [ ]:
arr=np.array([[[[[4,5]]]]])
print(arr.ndim)
arr.shape

5


(1, 1, 1, 1, 2)

In [ ]:
# Range
"""
Insted of doing manual or running a loop we can use range function

a = [1,2,3,4,.....100]

# Loop
l = []
for i in range(100)
  l.append(i)
"""
range = np.arange(100)
range1 = np.arange(0,100,2) #Start, stop , step
print(range)
range1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# Linspace
"""
The np.linspace() function in NumPy creates an array with a specified number
of elements that are evenly spaced between a starting and ending value.
"""
arr = np.linspace(1,100,10)# Start, Stop, Number Of Digits
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Logspace

The `np.logspace()` function in NumPy creates an array with elements that are evenly spaced on a logarithmic scale.

The parameters are:

- `start`: The starting value (as `base**start`).
- `stop`: The ending value (as `base**stop`).
- `num`: The number of samples to generate (default is 50).
- `endpoint`: If True (default), the `stop` value is included.
- `base`: The base of the logarithm (default is 10).

In [ ]:
# Basic logspace example
log_arr = np.logspace(1, 3, 5) # 5 points between 10^1 and 10^3
print(log_arr)

## np.zeros()

The `np.zeros()` function in NumPy creates a new array of a specified size, filled with zeros.

**How it works:**

You provide the desired shape of the array as an argument (a tuple for multi-dimensional arrays). `np.zeros()` then returns a NumPy array with that shape, where every element is `0.0` (by default, the data type is float).

**Where it is used:**

- **Initialization:** It's commonly used to initialize arrays before filling them with data. This is useful when you know the size of the array beforehand.
- **Placeholders:** Creating arrays of zeros can serve as placeholders in calculations or data structures.
- **Mathematical operations:** In some mathematical operations or algorithms, starting with an array of zeros is necessary.
- **Image processing:** Creating black images (represented by zeros in some formats) or initializing arrays for image manipulation.

In [ ]:
# 1D array of zeros
zeros_1d = np.zeros(5)
print("1D array of zeros:", zeros_1d)

# 2D array of zeros
zeros_2d = np.zeros((3, 4))# 3 rows , 4 Columns
print("\n2D array of zeros:\n", zeros_2d)

# 3D array of zeros
zeros_3d = np.zeros((4, 2, 2)) # 4 Matrix , 2 rows , 2 columns
print("\n3D array of zeros:\n", zeros_3d)

1D array of zeros: [0. 0. 0. 0. 0.]

2D array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3D array of zeros:
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


## np.ones()

The `np.ones()` function in NumPy creates a new array of a specified size, filled with ones.

**How it works:**

Similar to `np.zeros()`, you provide the desired shape of the array as an argument (a tuple for multi-dimensional arrays). `np.ones()` then returns a NumPy array with that shape, where every element is `1.0` (by default, the data type is float).

**Where it is used:**

- **Initialization:** It's used to initialize arrays with ones before performing operations that require a starting value of 1.
- **Creating masks:** Arrays of ones can be used to create masks for selecting or manipulating parts of other arrays.
- **Mathematical operations:** In some mathematical operations or algorithms, starting with an array of ones is necessary.

In [ ]:
# 1D array of ones
ones_1d = np.ones(5)
print("1D array of ones:", ones_1d)

# 2D array of ones
ones_2d = np.ones((3, 4))
print("\n2D array of ones:\n", ones_2d)

# 3D array of ones
ones_3d = np.ones((2, 3, 2))
print("\n3D array of ones:\n", ones_3d)

1D array of ones: [1. 1. 1. 1. 1.]

2D array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3D array of ones:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


## np.full()

The `np.full()` function in NumPy creates a new array of a specified shape, filled with a specified fill value.

**How it works:**

You provide the desired shape of the array as the first argument (a tuple for multi-dimensional arrays) and the fill value as the second argument. `np.full()` then returns a NumPy array with that shape, where every element is the specified fill value.

**Where it is used:**

- **Initialization with a specific value:** Unlike `np.zeros()` or `np.ones()`, `np.full()` allows you to initialize an array with any desired constant value.
- **Creating constant arrays:** Useful when you need an array where all elements are the same for calculations or comparisons.
- **Placeholders with a specific value:** Similar to `np.zeros()`, but with the flexibility to use any value.

In [ ]:
# Create a Basic np.full with Desired number
arr = np.full(10,5)
print(arr)

# Create a 3x3 array filled with the value 7
full_array = np.full((2, 3), 7) # Row , Coloumn , default value
print("Array filled with 7:\n", full_array)


[5 5 5 5 5 5 5 5 5 5]
Array filled with 7:
 [[7 7 7]
 [7 7 7]]


## np.empty()

The `np.empty()` function in NumPy creates a new array of a specified shape without initializing the entries. The values in the array will be whatever is currently in the memory location.

**How it works:**

You provide the desired shape of the array as an argument (a tuple for multi-dimensional arrays). `np.empty()` allocates memory for the array but does not fill it with any specific value (like zeros or ones). This makes it faster than `np.zeros()` or `np.ones()` if you plan to fill the array with your own data immediately.

**Where it is used:**

- **Performance:** When performance is critical and you know you will overwrite all elements of the array shortly after creation, `np.empty()` can be faster than `np.zeros()` or `np.ones()` in some cases.
- **Placeholder:** Creating an array of a specific size when you don't care about the initial values and will populate it later.

In [ ]:
# 1D empty array
empty_1d = np.empty(5)
print("1D empty array:", empty_1d)

# 2D empty array
empty_2d = np.empty((3, 4))
print("\n2D empty array:\n", empty_2d)

# 3D empty array
empty_3d = np.empty((2, 3, 2))
print("\n3D empty array:\n", empty_3d)

1D empty array: [1. 1. 1. 1. 1.]

2D empty array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3D empty array:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


## np.random.rand()

The `np.random.rand()` function in NumPy generates random numbers from a **uniform distribution** over the interval `[0, 1)`. This means that any value between 0 (inclusive) and 1 (exclusive) is equally likely to be generated.

**How it works:**

- When called with no arguments, it returns a single random float.
- When called with one or more arguments, it creates an array of the specified shape, filled with random floats.

**Where it is used:**

- **Simulations:** Generating random inputs for simulations.
- **Initialization:** Initializing arrays with random values (e.g., for weights in neural networks).
- **Testing:** Creating random data for testing purposes.

In [ ]:
# Generate a single random float between 0 and 1
random_scalar = np.random.rand()
print("Single random float:", random_scalar)

# Generate a 1D array of 5 random floats
random_1d_array = np.random.rand(5)
print("\n1D array of random floats:", random_1d_array)

# Generate a 2D array (3x4) of random floats
random_2d_array = np.random.rand(3, 4)
print("\n2D array of random floats:\n", random_2d_array)

Single random float: 0.8771799305719019

1D array of random floats: [0.36768712 0.30291491 0.7465615  0.84491646 0.71755942]

2D array of random floats:
 [[0.36837535 0.56851702 0.63788502 0.31005341]
 [0.11185736 0.08671013 0.0532535  0.11025934]
 [0.28561666 0.29712602 0.8163293  0.81247867]]


## np.random.randn()

The `np.random.randn()` function in NumPy generates random numbers from the **standard normal distribution** (also known as the Gaussian distribution).

**How it works:**

- The standard normal distribution has a mean of 0 and a variance of 1.
- When called with no arguments, it returns a single random float from this distribution.
- When called with one or more arguments, it creates an array of the specified shape, filled with random floats from this distribution.

**Where it is used:**

- **Statistics and probability:** Generating random numbers from a normal distribution is fundamental in many statistical analyses and probability simulations.
- **Machine learning:** Used in various machine learning algorithms, particularly for initializing weights in neural networks or generating noise.
- **Modeling:** Creating random data that follows a normal distribution for modeling real-world phenomena.

In [ ]:
# Generate a single random number from the standard normal distribution
random_normal_scalar = np.random.randn()
print("Single random number from standard normal distribution:", random_normal_scalar)

# Generate a 1D array of 5 random numbers from the standard normal distribution
random_normal_1d_array = np.random.randn(5)
print("\n1D array of random numbers from standard normal distribution:", random_normal_1d_array)

# Generate a 2D array (3x4) of random numbers from the standard normal distribution
random_normal_2d_array = np.random.randn(3, 4)
print("\n2D array of random numbers from standard normal distribution:\n", random_normal_2d_array)

Single random number from standard normal distribution: -0.1500967831581858

1D array of random numbers from standard normal distribution: [ 0.02599189 -0.31327288  0.50050587 -1.57506184  0.65291151]

2D array of random numbers from standard normal distribution:
 [[-0.42567294  0.96485796  2.35894991  1.40208376]
 [ 0.09589253 -0.44771054 -0.87946993  0.16896834]
 [-0.32112064  0.1532938  -0.39446227  0.42176175]]


In [ ]:
# Normal distribution: mean=50, std=10
normal_arr = 50 + 10 * np.random.randn(5)

# Standard normal distribution: mean=0, std=1
std_normal_arr =  np.random.randn(5)

print(normal_arr)
print(std_normal_arr)


[54.70812181 53.95757244 52.44623509 37.33728129 52.59628424]
[ 1.03488041  0.17380519  0.48277526  1.71965537 -0.13334747]


## np.random.randint()

The `np.random.randint()` function in NumPy generates random integers from a "discrete uniform" distribution over the specified interval.

**How it works:**

- It takes at least one argument, `low`, which is the lowest integer to be drawn from the distribution (inclusive).
- It can optionally take a second argument, `high`, which is the highest integer to be drawn from the distribution (exclusive). If `high` is not specified, the results are drawn from `[0, low)`.
- The `size` parameter (optional) specifies the shape of the output array.

**Where it is used:**

- **Simulations:** Generating random integer outcomes (e.g., rolling a die, picking a random item from a list).
- **Creating sample data:** Generating arrays of random integers for testing or examples.
- **Indexing and selection:** Generating random indices to select elements from an array.

In [ ]:
# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_integer_scalar = np.random.randint(10)
print("Single random integer (0 to 9):", random_integer_scalar)

# Generate a single random integer between 1 (inclusive) and 11 (exclusive)
random_integer_scalar_range = np.random.randint(1, 11)
print("Single random integer (1 to 10):", random_integer_scalar_range)

# Generate a 1D array of 5 random integers between 0 and 10
random_integer_1d_array = np.random.randint(10, size=5)
print("\n1D array of random integers (0 to 9):\n", random_integer_1d_array)

# Generate a 2D array (3x4) of random integers between 1 and 100
random_integer_2d_array = np.random.randint(1, 101, size=(3, 4))
print("\n2D array of random integers (1 to 100):\n", random_integer_2d_array)

Single random integer (0 to 9): 7
Single random integer (1 to 10): 2

1D array of random integers (0 to 9):
 [7 2 9 5 0]

2D array of random integers (1 to 100):
 [[17 95 77 23]
 [74 84 93 15]
 [74 53 35  4]]


## NumPy Data Types (dtypes)

NumPy provides a wide range of data types to handle various kinds of numerical data. These data types, or "dtypes", are essential for efficient storage and manipulation of arrays. When you create a NumPy array, it automatically infers the data type based on the input data, but you can also explicitly specify the dtype.

Here are some of the commonly used NumPy data types:

- **Integers:**
    - `int8`, `int16`, `int32`, `int64`: Signed integers of different sizes.
    - `uint8`, `uint16`, `uint32`, `uint64`: Unsigned integers of different sizes.
- **Floats:**
    - `float16`, `float32`, `float64`: Floating-point numbers of different precision.
- **Booleans:**
    - `bool`: Boolean values (True or False).
- **Complex Numbers:**
    - `complex64`, `complex128`: Complex numbers with different precision.
- **Strings:**
    - `string_`: Fixed-length string type.
    - `unicode_`: Fixed-length Unicode string type.

Specifying the correct data type is important for memory efficiency and performance, as well as ensuring the correct behavior of mathematical operations.

In [ ]:
# Integer data types
int_array = np.array([1, 2, 3], dtype=np.int32)
print("Integer array (int32):", int_array, int_array.dtype)

uint_array = np.array([100, 200, 255], dtype=np.uint8) #Uint stores only the int from 0 to 255, Uses low space, and more effective
print("Unsigned integer array (uint8):", uint_array, uint_array.dtype)

int_array64 = np.array([1723, 289149, 30713498], dtype=np.int64)
print("Integer array (int64):", int_array64, int_array64.dtype)

Integer array (int32): [1 2 3] int32
Unsigned integer array (uint8): [100 200 255] uint8
Integer array (int32): [    1723   289149 30713498] int64


In [ ]:
# Floating-point data types
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print("Float array (float64):", float_array, float_array.dtype)

float32_array = np.array([1.1, 2.2, 3.3], dtype=np.float32)
print("Float array (float32):", float32_array, float32_array.dtype)

float16_array = np.array([1.1, 2.2, 3.3], dtype=np.float16)
print("Float array (float16):", float16_array, float16_array.dtype)

Float array (float64): [1.1 2.2 3.3] float64
Float array (float32): [1.1 2.2 3.3] float32
Float array (float16): [1.1 2.2 3.3] float16


In [ ]:
# Boolean data type
bool_array = np.array([True, False, True], dtype=np.bool_)
print("Boolean array:", bool_array, bool_array.dtype)

Boolean array: [ True False  True] bool


In [ ]:
# Complex data type
complex_array = np.array([1 + 2j, 3 - 4j], dtype=np.complex128)
print("Complex array:", complex_array, complex_array.dtype)

Complex array: [1.+2.j 3.-4.j] complex128


In [ ]:
# String data types
string_array = np.array(['hello', 'world'], dtype=np.bytes_)
print("String array (string_):", string_array, string_array.dtype)

unicode_array = np.array(['Hey', 'Guys'], dtype=np.str_)
print("Unicode array (unicode_):", unicode_array, unicode_array.dtype)

String array (string_): [b'hello' b'world'] |S5
Unicode array (unicode_): ['Hey' 'Guys'] <U4


## Type Casting (Changing Data Types)

Type casting, also known as type conversion, in NumPy refers to the process of changing the data type (`dtype`) of elements within an array. This is a common operation when you need to perform calculations that require a specific data type or when you want to save memory by using a smaller data type.

NumPy provides several ways to change the data type of an array:

1.  **Using the `dtype` parameter during array creation:** You can specify the desired data type when you initially create a NumPy array using functions like `np.array()`, `np.zeros()`, `np.ones()`, etc.
2.  **Using the `.astype()` method:** This is the most common and flexible way to change the data type of an existing array. The `.astype()` method returns a *new* array with the specified data type.

**Why is type casting important?**

-   **Memory Efficiency:** Using smaller data types (e.g., `int16` instead of `int64`) can significantly reduce memory usage, especially for large arrays.
-   **Performance:** Certain operations might be faster with specific data types.
-   **Compatibility:** Sometimes, you need to convert data types to ensure compatibility with other libraries or functions.
-   **Data Interpretation:** Changing the data type can alter how the numbers are interpreted (e.g., converting a float to an integer truncates the decimal part).

In [ ]:
# Create an array with a default data type (likely int64)
int_array = np.array([1, 2, 3, 4, 5])
print("Original array:", int_array, int_array.dtype)

# Cast the integer array to float64
float_array = int_array.astype(np.float64)
print("Array after casting to float64:", float_array, float_array.dtype)

# Cast the float array to int32
int32_array = float_array.astype(np.int32)
print("Array after casting to int32:", int32_array, int32_array.dtype)

# Create a float array
float_array_2 = np.array([1.1, 2.9, 3.5, 4.2, 5.7])
print("\nOriginal float array:", float_array_2, float_array_2.dtype)

# Cast the float array to integer (truncates the decimal part)
int_array_2 = float_array_2.astype(int) # You can also use the Python built-in type
print("Array after casting to int:", int_array_2, int_array_2.dtype)

# Casting a boolean array to integer
bool_array = np.array([True, False, True])
print("\nOriginal boolean array:", bool_array, bool_array.dtype)

int_from_bool = bool_array.astype(int)
print("Array after casting boolean to int:", int_from_bool, int_from_bool.dtype)

arr = np.array ([1,2,3,4,5])
print(arr, arr.dtype)
new_arr = arr.astype(np.float64)
print(new_arr, new_arr.dtype)

Original array: [1 2 3 4 5] int64
Array after casting to float64: [1. 2. 3. 4. 5.] float64
Array after casting to int32: [1 2 3 4 5] int32

Original float array: [1.1 2.9 3.5 4.2 5.7] float64
Array after casting to int: [1 2 3 4 5] int64

Original boolean array: [ True False  True] bool
Array after casting boolean to int: [1 0 1] int64
[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64


## Array Reshaping, Ravel, and Flatten

NumPy provides functions to change the shape of an array without changing the data it contains. This is particularly useful when you need to rearrange data for different operations or algorithms.

### Reshaping (`.reshape()`)

The `.reshape()` method allows you to change the dimensions of an array into a new shape. The new shape must have the same number of elements as the original array.

In [ ]:
# Example of reshaping
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape((2, 3)) # Reshape to a 2x3 matrix
print("Original array:", original_array)
print("Reshaped array (2x3):\n", reshaped_array)

reshaped_array_3d = original_array.reshape((3, 2, 1)) # Reshape to a 3x2x1 3D array
# Here 3 is the No. of Matrix, 2 is rows and 1 is coloumns
print("Reshaped array (3x2x1):\n", reshaped_array_3d)

# Example of reshaping with -1
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
reshaped_array = original_array.reshape((-1,3)) # Reshape to have 3 columns, infer rows. -1 means do automatically the calculation for the Dimensions of the matrix
# You cant able to give as ((-1,-1)) , it doesnt do both automaticlly ,atlest you need to give one (3,-1) or (-1,3)
print("Original array:", original_array)
print("Reshaped array (inferred rows):\n", reshaped_array)

Original array: [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped array (3x2x1):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (inferred rows):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Ravel (`.ravel()`)

The `.ravel()` method returns a **view** of the original array whenever possible. This means that if you modify the raveled array, the changes will also be reflected in the original array. If a view is not possible (e.g., due to memory layout), it will return a copy, but this is less common. It always returns a flattened, 1-dimensional array.

### Flatten (`.flatten()`)

The `.flatten()` method always returns a **copy** of the original array. This means that if you modify the flattened array, the original array will remain unchanged. It also always returns a flattened, 1-dimensional array.

### Key Difference: View vs. Copy

The crucial difference between `ravel()` and `flatten()` lies in whether they return a view or a copy of the original array:

-   **`ravel()`**: Returns a **view** (usually), so changes to the raveled array affect the original array.
-   **`flatten()`**: Returns a **copy**, so changes to the flattened array do **not** affect the original array.

Use `ravel()` when you want to work with a flattened version of the array and potentially modify the original array through the flattened view. Use `flatten()` when you need an independent, flattened copy of the array.

In [ ]:
# Example of flatten and ravel
original_array = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = original_array.flatten() # Flatten array creates a copy of the orginal array and then if we did any changes that happens on the copy not on the orginal
raveled_array = original_array.ravel() # Ravel array just shows the view of the Orginal array In the 1 Dimesional and if we change any that changes in the orginal itself
# Thats the major difference of the two types of Flatten and Ravel array.

print("Original 2D array:\n", original_array)
print("Flattened array:", flattened_array)
print("Raveled array:", raveled_array)

# Demonstrating the difference (modifying the flattened/raveled array)
flattened_array[0] = 100
raveled_array[0] = 200

print("\nOriginal array after modifying flattened:", original_array) # Original is unchanged
print("Flattened array after modification:", flattened_array)

print("\nOriginal array after modifying raveled:\n", original_array) # Original is changed (if ravel returned a view)
print("Raveled array after modification:", raveled_array)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]
Raveled array: [1 2 3 4 5 6]

Original array after modifying flattened: [[200   2   3]
 [  4   5   6]]
Flattened array after modification: [100   2   3   4   5   6]

Original array after modifying raveled:
 [[200   2   3]
 [  4   5   6]]
Raveled array after modification: [200   2   3   4   5   6]


## NumPy Arithmetic Operators

NumPy arrays allow for element-wise arithmetic operations. This means that when you apply an arithmetic operator (like +, -, *, /, etc.) to two NumPy arrays of the same shape, the operation is performed individually on each corresponding element. If you apply an operator with a scalar (a single number), the operation is performed on every element of the array.

Here are some common arithmetic operators you can use with NumPy arrays:

-   **Addition (`+`)**: Adds corresponding elements of two arrays or adds a scalar to each element of an array.
-   **Subtraction (`-`)**: Subtracts corresponding elements of two arrays or subtracts a scalar from each element of an array.
-   **Multiplication (`*`)**: Multiplies corresponding elements of two arrays or multiplies each element of an array by a scalar. This is **element-wise** multiplication, not matrix multiplication.
-   **Division (`/`)**: Divides corresponding elements of two arrays or divides each element of an array by a scalar.
-   **Floor Division (`//`)**: Performs integer division element-wise.
-   **Modulo (`%`)**: Computes the remainder of the division element-wise.
-   **Exponentiation (`**`)**: Raises each element of the first array to the power of the corresponding element in the second array, or raises each element of an array to the power of a scalar.

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
scalar = 2

# Addition
add_result = arr1 + arr2
print("Addition:", add_result)

# Subtraction
sub_result = arr1 - arr2
print("Subtraction:", sub_result)

# Multiplication (element-wise)
mul_result = arr1 * arr2
print("Multiplication:", mul_result)

# Division
div_result = arr1 / arr2
print("Division:", div_result)

# Floor Division
floor_div_result = arr1 // scalar
print("Floor Division:", floor_div_result)

# Modulo
mod_result = arr2 % scalar
print("Modulo:", mod_result)

# Exponentiation
exp_result = arr1 ** scalar
print("Exponentiation:", exp_result)

# Arithmetic operations with a scalar
scalar_add = arr1 + scalar
print("Scalar Addition:", scalar_add)

scalar_mul = arr2 * scalar
print("Scalar Multiplication:", scalar_mul)

print("\n--- 2D Array Arithmetic ---")
arr_2d_1 = np.array([[1, 2], [3, 4]])
arr_2d_2 = np.array([[5, 6], [7, 8]])

print("2D Array 1:\n", arr_2d_1)
print("2D Array 2:\n", arr_2d_2)

print("2D Array Addition:\n", arr_2d_1 + arr_2d_2)
print("2D Array Multiplication (element-wise):\n", arr_2d_1 * arr_2d_2)
print("2D Array Division:\n", arr_2d_1 / arr_2d_2)

print("\n--- 3D Array Arithmetic ---")
arr_3d_1 = np.arange(1, 9).reshape((2, 2, 2))
arr_3d_2 = np.arange(9, 17).reshape((2, 2, 2))

print("3D Array 1:\n", arr_3d_1)
print("3D Array 2:\n", arr_3d_2)

print("3D Array Addition:\n", arr_3d_1 + arr_3d_2)
print("3D Array Subtraction:\n", arr_3d_1 - arr_3d_2)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Floor Division: [0 1 1 2]
Modulo: [1 0 1 0]
Exponentiation: [ 1  4  9 16]
Scalar Addition: [3 4 5 6]
Scalar Multiplication: [10 12 14 16]

--- 2D Array Arithmetic ---
2D Array 1:
 [[1 2]
 [3 4]]
2D Array 2:
 [[5 6]
 [7 8]]
2D Array Addition:
 [[ 6  8]
 [10 12]]
2D Array Multiplication (element-wise):
 [[ 5 12]
 [21 32]]
2D Array Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

--- 3D Array Arithmetic ---
3D Array 1:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3D Array 2:
 [[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
3D Array Addition:
 [[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]
3D Array Subtraction:
 [[[-8 -8]
  [-8 -8]]

 [[-8 -8]
  [-8 -8]]]


In [ ]:
# Example of arithmetic operation on arrays with different shapes
arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([5, 6])

# Trying to add arrays with incompatible shapes
# This will raise a ValueError because the shapes (4,) and (2,) are not compatible for broadcasting
# add_different_shapes = arr_a + arr_b

# Error Explanation:
# A ValueError occurs when trying to perform element-wise operations
# on arrays with shapes that cannot be broadcast together.
# In this case, array 'arr_a' has shape (4,) and 'arr_b' has shape (2,).
# NumPy attempts to align the dimensions for the operation, but it fails
# because the sizes of the dimensions from the end are not compatible (4 vs 2).

## NumPy Universal Functions (ufuncs)

Universal functions, or ufuncs, are NumPy functions that operate element-by-element on arrays. They are "universal" in the sense that they can operate on different data types and perform broadcasting. Ufuncs are designed to be highly optimized and are implemented in compiled code (like C), making them significantly faster than equivalent Python functions or loops for large arrays.

**Key Characteristics of ufuncs:**

-   **Element-wise operation:** Ufuncs apply the same operation to each element of the input array(s) to produce an output array.
-   **Broadcasting:** They automatically handle broadcasting, allowing you to perform operations on arrays of different shapes if they are compatible according to broadcasting rules.
-   **Speed:** Due to their implementation in compiled code, ufuncs are very fast.
-   **Methods:** Ufuncs have several methods that allow for more complex operations, such as `reduce`, `accumulate`, `outer`, and `reduceat`.

Many of the arithmetic and mathematical functions we've already seen are implemented as ufuncs (e.g., `np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.sqrt`, `np.sin`, `np.cos`). Using the operator syntax (like `+`, `-`, `*`) is often a convenient shorthand for the corresponding ufunc.

In [ ]:
# Example of mathematical functions

arr = np.array([1, 4, 9, 16, 25])

# Square root: Computes the non-negative square root of each element.
sqrt_arr = np.sqrt(arr)
print("Square root:", sqrt_arr)

# Sine (element-wise): Computes the sine of each element (in radians).
sin_arr = np.sin(arr)
print("Sine:", sin_arr)

# Cosine (element-wise): Computes the cosine of each element (in radians).
cos_arr = np.cos(arr)
print("Cosine:", cos_arr)

# Logarithm (natural log): Computes the natural logarithm of each element.
log_arr = np.log(arr)
print("Natural logarithm:", log_arr)

# Exponential: Computes the exponential of each element (e^x).
exp_arr = np.exp(arr)
print("Exponential:", exp_arr)

In [ ]:
# Example of statistical functions

arr = np.array([10, 20, 30, 40, 50])

# Mean: Computes the arithmetic mean of the array elements.
mean_val = np.mean(arr)
print("Mean:", mean_val)

# Median: Computes the median of the array elements.
median_val = np.median(arr)
print("Median:", median_val)

# Standard deviation: Computes the standard deviation of the array elements.
std_val = np.std(arr)
print("Standard deviation:", std_val)

# Variance: Computes the variance of the array elements.
var_val = np.var(arr)
print("Variance:", var_val)

# Sum: Computes the sum of the array elements.
sum_val = np.sum(arr)
print("Sum:", sum_val)

# Minimum: Finds the minimum value in the array.
min_val = np.min(arr)
print("Minimum:", min_val)

# Maximum: Finds the maximum value in the array.
max_val = np.max(arr)
print("Maximum:", max_val)

#How to use any Fucntion in matrix, we can use them using the axis called (row 0 ,column 1)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ("Orginal matrix\n",matrix)
print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))


Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951
Variance: 200.0
Sum: 150
Minimum: 10
Maximum: 50
Orginal matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


## NumPy Indexing and Slicing

NumPy array indexing and slicing are powerful ways to access and modify elements or subsets of an array. They are similar to Python lists but with extensions for multi-dimensional arrays.

### Indexing

Indexing allows you to access individual elements of an array using their position (index).

- **1D arrays:** You use a single index within square brackets `[]`. Indices start from 0.
- **Multi-dimensional arrays:** You use a comma-separated tuple of indices, one for each dimension. For example, `arr[row_index, column_index]` for a 2D array. You can also use a list of indices to select multiple specific elements.

### Slicing

Slicing allows you to extract a portion (a "slice") of an array. It's defined by a start, stop, and step value, separated by colons (`:`).

- **`start:stop`:** Extracts elements from `start` up to (but not including) `stop`.
- **`start:stop:step`:** Extracts elements from `start` up to (but not including) `stop`, with a step size of `step`.
- **Omitting `start`:** Assumes the slice starts from the beginning of the dimension.
- **Omitting `stop`:** Assumes the slice goes to the end of the dimension.
- **Omitting `step`:** Assumes a step size of 1.
- **Negative indices:** Can be used to index from the end of the array (-1 is the last element, -2 is the second to last, and so on).

For multi-dimensional arrays, you can slice along each dimension independently using comma-separated slices. For example, `arr[row_slice, column_slice]`.

In [ ]:
# 1D array indexing and slicing
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing
print("Element at index 3:", arr_1d[3])
print("Element at last index:", arr_1d[-1])

# Slicing
print("Elements from index 2 to 7:", arr_1d[2:8])
print("Elements from the beginning to index 5:", arr_1d[:6])
print("Elements from index 5 to the end:", arr_1d[5:])
print("Every other element:", arr_1d[::2]) #Start,stop,step
print("Elements in reverse order:", arr_1d[::-1]) #Start,stop,step
print("Elements from index 7 with step -2:", arr_1d[7::-2]) #Start,stop,step


# 2D array indexing and slicing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\nOriginal 2D array:\n", arr_2d)

# Indexing a single element
print("Element at row 1, column 2:", arr_2d[1, 2]) # Remember indexing starts from 0

# Slicing rows
print("First row:", arr_2d[0, :])
print("Last two rows:\n", arr_2d[1:, :])

# Slicing columns
print("Second column:", arr_2d[:, 1])
print("First two columns:\n", arr_2d[:, :2])

# Slicing both rows and columns
print("Subset (top-right 2x2):\n", arr_2d[:2, 1:])

# Using a list of indices to select specific rows or columns
print("Specific rows (0 and 2):\n", arr_2d[[0, 2], :])
print("Specific columns (0 and 2):\n", arr_2d[:, [0, 2]])

# Using boolean indexing
print("Elements greater than 5:\n", arr_2d[arr_2d > 5])

Element at index 3: 3
Element at last index: 9
Elements from index 2 to 7: [2 3 4 5 6 7]
Elements from the beginning to index 5: [0 1 2 3 4 5]
Elements from index 5 to the end: [5 6 7 8 9]
Every other element: [0 2 4 6 8]
Elements in reverse order: [9 8 7 6 5 4 3 2 1 0]
Elements from index 7 with step -2: [7 5 3 1]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
First row: [1 2 3]
Last two rows:
 [[4 5 6]
 [7 8 9]]
Second column: [2 5 8]
First two columns:
 [[1 2]
 [4 5]
 [7 8]]
Subset (top-right 2x2):
 [[2 3]
 [5 6]]
Specific rows (0 and 2):
 [[1 2 3]
 [7 8 9]]
Specific columns (0 and 2):
 [[1 3]
 [4 6]
 [7 9]]
Elements greater than 5:
 [6 7 8 9]


## np.take()

The `np.take()` function in NumPy is used to take elements from an array along an axis. It's similar to fancy indexing but provides more control over the axis from which elements are taken.

**How it works:**

- It takes an array (`a`), an array of indices (`indices`), and an optional axis (`axis`) as arguments.
- It returns a new array containing the elements of `a` at the given `indices`.
- If `axis` is not specified, the array is flattened before taking the elements.
- If `axis` is specified, elements are taken along that axis.

**Where it is used:**

- **Selecting specific elements:** You can use `np.take()` to select elements at particular indices, which can be useful when the indices are stored in another array.
- **Working with multi-dimensional arrays:** It allows you to select elements along a specific dimension, which can be more convenient than complex slicing in some cases.

In [ ]:
import numpy as np

# 1D array example
arr_1d = np.array([10, 20, 30, 40, 50])
indices_1d = np.array([0, 2, 4])

# Take elements at specified indices
taken_1d = np.take(arr_1d, indices_1d)
print("Original 1D array:", arr_1d)
print("Indices to take:", indices_1d)
print("Elements taken from 1D array:", taken_1d)

# 2D array example
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Take elements along axis 0 (rows)
indices_rows = np.array([0, 2])
taken_rows = np.take(arr_2d, indices_rows, axis=0)
print("\nOriginal 2D array:\n", arr_2d)
print("Indices to take along axis 0:", indices_rows)
print("Elements taken along axis 0:\n", taken_rows)

# Take elements along axis 1 (columns)
indices_cols = np.array([0, 2])
taken_cols = np.take(arr_2d, indices_cols, axis=1)
print("\nIndices to take along axis 1:", indices_cols)
print("Elements taken along axis 1:\n", taken_cols)

# Take elements from the flattened array
indices_flat = np.array([1, 5, 7])
taken_flat = np.take(arr_2d, indices_flat)
print("\nIndices to take from flattened array:", indices_flat)
print("Elements taken from flattened array:", taken_flat)

Original 1D array: [10 20 30 40 50]
Indices to take: [0 2 4]
Elements taken from 1D array: [10 30 50]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Indices to take along axis 0: [0 2]
Elements taken along axis 0:
 [[1 2 3]
 [7 8 9]]

Indices to take along axis 1: [0 2]
Elements taken along axis 1:
 [[1 3]
 [4 6]
 [7 9]]

Indices to take from flattened array: [1 5 7]
Elements taken from flattened array: [2 6 8]


## np.nditer()

The `np.nditer()` function in NumPy provides a flexible way to iterate over elements of an array. It's a powerful tool for efficiently processing elements in multi-dimensional arrays, especially when you need more control over the iteration order or want to perform operations on the elements during iteration.

**How it works:**

- `np.nditer()` returns an iterator object that allows you to loop through the elements of one or more arrays.
- By default, it iterates over the array in a C-style (row-major) order, flattening the array.
- You can control the iteration order and behavior using various flags and options.

**Key Features and Use Cases:**

- **Efficient Iteration:** `nditer` is generally more efficient than nested Python loops for iterating over large NumPy arrays.
- **Multi-Array Iteration:** It can iterate over multiple arrays simultaneously, which is useful for element-wise operations on corresponding elements of different arrays.
- **Iteration Order Control:** You can specify the iteration order (e.g., 'C' for row-major, 'F' for column-major, 'A' for any order).
- **External Loop:** You can use an external loop to iterate over blocks of elements.
- **Operand Flags:** Flags like 'readwrite' allow you to modify the array elements during iteration.

In [ ]:
import numpy as np

# 1D array iteration
arr_1d = np.array([1, 2, 3, 4, 5])
print("Iterating over a 1D array:")
for x in np.nditer(arr_1d):
    print(x)

for i in np.nditer(arr_1d):
    print(i, end="")

# 2D array iteration (default C-style)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nIterating over a 2D array (default C-style):")
for x in np.nditer(arr_2d):
    print(x)

# 2D array iteration (F-style - column-major)
print("\nIterating over a 2D array (F-style):")
for x in np.nditer(arr_2d, order='F'):
    print(x)

# Iterating over multiple arrays simultaneously
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("\nIterating over multiple arrays:")
for x, y in np.nditer([arr1, arr2]):
    print(f"{x} + {y} = {x + y}")

# Iterating with 'readwrite' flag to modify elements
arr_modify = np.array([1, 2, 3, 4])
print("\nModifying elements during iteration:")
for x in np.nditer(arr_modify, op_flags=['readwrite']):
    x[...] = x * 2  # Modify the element in-place
print("Modified array:", arr_modify)

# Iterating with an external loop
arr_external = np.arange(12).reshape(3, 4)
print("\nIterating with an external loop (over rows):")
for row in np.nditer(arr_external, flags=['external_loop'], order='C'):
    print(row)


Iterating over a 1D array:
1
2
3
4
5
12345
Iterating over a 2D array (default C-style):
1
2
3
4
5
6

Iterating over a 2D array (F-style):
1
4
2
5
3
6

Iterating over multiple arrays:
1 + 4 = 5
2 + 5 = 7
3 + 6 = 9

Modifying elements during iteration:
Modified array: [2 4 6 8]

Iterating with an external loop (over rows):
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## np.ndenumerate()

The `np.ndenumerate()` function in NumPy provides an iterator that yields pairs of `(index, value)` for each element in an array, where `index` is a tuple representing the multi-dimensional index of the element and `value` is the element itself.

**How it works:**

- It takes a NumPy array as input.
- It returns an iterator that goes through each element of the array.
- For each element, it returns a tuple containing the index (as a tuple) and the value of that element.

**Where it is used:**

- **Iterating with indices:** When you need to access both the index and the value of each element during iteration, especially for multi-dimensional arrays.
- **Conditional operations based on index:** Performing operations on elements based on their position in the array.
- **Debugging and inspection:** Examining the elements of an array along with their corresponding indices.

In [ ]:
import numpy as np

# 1D array example
arr_1d = np.array([10, 20, 30, 40, 50])
print("Iterating over a 1D array with ndenumerate:")
for index, value in np.ndenumerate(arr_1d):
    print(f"Index: {index}, Value: {value}")

# 2D array example
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nIterating over a 2D array with ndenumerate:")
for index, value in np.ndenumerate(arr_2d):
    print(f"Index: {index}, Value: {value}")

# 3D array example
arr_3d = np.arange(8).reshape((2, 2, 2))
print("\nIterating over a 3D array with ndenumerate:")
for index, value in np.ndenumerate(arr_3d):
    print(f"Index: {index}, Value: {value}")

Iterating over a 1D array with ndenumerate:
Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30
Index: (3,), Value: 40
Index: (4,), Value: 50

Iterating over a 2D array with ndenumerate:
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9

Iterating over a 3D array with ndenumerate:
Index: (0, 0, 0), Value: 0
Index: (0, 0, 1), Value: 1
Index: (0, 1, 0), Value: 2
Index: (0, 1, 1), Value: 3
Index: (1, 0, 0), Value: 4
Index: (1, 0, 1), Value: 5
Index: (1, 1, 0), Value: 6
Index: (1, 1, 1), Value: 7


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Transposed array\n",arr.transpose())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed array
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## NumPy Transpose (`.transpose()`)

The `.transpose()` method in NumPy is used to permute the dimensions of an array. For a 2D array, this means swapping rows and columns. For higher-dimensional arrays, it rearranges the axes according to a specified order.

**How it works:**

- For a 2D array, `arr.transpose()` returns a view of the array with rows and columns swapped.
- For an n-dimensional array, `arr.transpose(*axes)` returns a view with the axes permuted according to the tuple of axes provided. If no axes are specified, it reverses the order of the axes.

**Where it is used:**

- **Matrix operations:** Transposing matrices is a fundamental operation in linear algebra for calculations like matrix multiplication.
- **Data manipulation:** Rearranging data for analysis or visualization purposes.
- **Compatibility:** Changing the order of dimensions to match the requirements of other functions or libraries.

In [ ]:
import numpy as np

# 2D array transpose
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original 2D array:\n", arr_2d)
print("Transposed 2D array:\n", arr_2d.transpose())

# 3D array transpose
arr_3d = np.arange(24).reshape((2, 3, 4))
print("\nOriginal 3D array shape:", arr_3d.shape)
print("Original 3D array:\n", arr_3d)

# Transpose with default axis permutation (reverses axes order)
arr_3d_transpose_default = arr_3d.transpose()
print("\nTransposed 3D array (default - axes reversed) shape:", arr_3d_transpose_default.shape)
print("Transposed 3D array (default):\n", arr_3d_transpose_default)

# Transpose with specified axis permutation (e.g., swap axis 0 and 1)
arr_3d_transpose_specified = arr_3d.transpose((1, 0, 2)) # Swap axis 0 and 1
print("\nTransposed 3D array (axes 0 and 1 swapped) shape:", arr_3d_transpose_specified.shape)
print("Transposed 3D array (axes 0 and 1 swapped):\n", arr_3d_transpose_specified)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Transposed 2D array:
 [[1 4]
 [2 5]
 [3 6]]

Original 3D array shape: (2, 3, 4)
Original 3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transposed 3D array (default - axes reversed) shape: (4, 3, 2)
Transposed 3D array (default):
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]

Transposed 3D array (axes 0 and 1 swapped) shape: (3, 2, 4)
Transposed 3D array (axes 0 and 1 swapped):
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


## NumPy Swapaxes (`np.swapaxes()`)

The `np.swapaxes()` function in NumPy is used to swap two specified axes of an array. This is similar to `transpose()`, but `swapaxes()` is specifically designed for swapping only two axes at a time.

**How it works:**

- It takes an array (`a`) and two axis indices (`axis1`, `axis2`) as arguments.
- It returns a view of the array with the data from the two specified axes swapped.

**Where it is used:**

- **Rearranging dimensions:** Convenient for quickly changing the order of two dimensions in a multi-dimensional array.
- **Preparing data for operations:** Sometimes certain operations require specific dimensions to be in a particular order.
- **Compatibility:** Aligning array dimensions with the expectations of other functions or libraries.

In [ ]:
import numpy as np

# Create a 3D array
arr_3d = np.arange(24).reshape((2, 3, 4))
print("Original 3D array shape:", arr_3d.shape)
print("Original 3D array:\n", arr_3d)

# Swap axis 0 and axis 1
swapped_0_1 = np.swapaxes(arr_3d, 0, 1)
print("\nArray after swapping axis 0 and 1 shape:", swapped_0_1.shape)
print("Array after swapping axis 0 and 1:\n", swapped_0_1)

# Swap axis 1 and axis 2
swapped_1_2 = np.swapaxes(arr_3d, 1, 2)
print("\nArray after swapping axis 1 and 2 shape:", swapped_1_2.shape)
print("Array after swapping axis 1 and 2:\n", swapped_1_2)

## NumPy Concatenation (`np.concatenate()`)

The `np.concatenate()` function in NumPy is used to join a sequence of arrays along an existing axis. It's a versatile function that allows you to combine arrays of the same shape (except for the dimension along which you are concatenating).

**How it works:**

- It takes a sequence of arrays (e.g., a list or tuple of arrays) as the first argument.
- The second argument, `axis`, specifies the axis along which the arrays will be joined.
    - If `axis=0` (default), the arrays are stacked vertically (row-wise).
    - If `axis=1`, the arrays are stacked horizontally (column-wise) for 2D arrays, and similarly for higher dimensions.
- All arrays in the sequence must have the same shape, except for the dimension along the specified axis.

**Where it is used:**

- **Combining data:** Merging different datasets or parts of arrays into a single array.
- **Stacking results:** Combining the output of different operations or models.
- **Preparing data for input:** Formatting data into the required shape for machine learning models or other functions.

In [ ]:
import numpy as np

# Concatenating 1D arrays
arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])

concatenated_1d = np.concatenate((arr1_1d, arr2_1d))
print("Concatenated 1D array:", concatenated_1d)

# Concatenating 2D arrays (along axis 0 - rows)
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

concatenated_2d_axis0 = np.concatenate((arr1_2d, arr2_2d), axis=0)
print("\nConcatenated 2D array (axis=0):\n", concatenated_2d_axis0)

# Concatenating 2D arrays (along axis 1 - columns)
concatenated_2d_axis1 = np.concatenate((arr1_2d, arr2_2d), axis=1)
print("\nConcatenated 2D array (axis=1):\n", concatenated_2d_axis1)

# Concatenating arrays with different shapes (will cause an error)
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6, 7], [8, 9, 10]])

# The following line would raise a ValueError because the shapes are incompatible
# concatenated_error = np.concatenate((arr_a, arr_b), axis=1)
# print("\nConcatenating arrays with different shapes (axis=1):\n", concatenated_error)

# Concatenating 3D arrays (along axis 0)
arr1_3d = np.arange(4).reshape(1, 2, 2)
arr2_3d = np.arange(4, 8).reshape(1, 2, 2)

concatenated_3d_axis0 = np.concatenate((arr1_3d, arr2_3d), axis=0)
print("\nConcatenated 3D array (axis=0):\n", concatenated_3d_axis0)

# Concatenating 3D arrays (along axis 2)
arr3_3d = np.arange(8).reshape(2, 2, 2)
arr4_3d = np.arange(8, 16).reshape(2, 2, 2)

concatenated_3d_axis2 = np.concatenate((arr3_3d, arr4_3d), axis=2)
print("\nConcatenated 3D array (axis=2):\n", concatenated_3d_axis2)

## NumPy Vertical Stack (`np.vstack()`) and Horizontal Stack (`np.hstack()`)

NumPy provides `np.vstack()` and `np.hstack()` as convenient functions for stacking arrays vertically and horizontally, respectively. These are essentially specialized cases of `np.concatenate()`.

### Vertical Stack (`np.vstack()`)

`np.vstack()` stacks arrays in sequence vertically (row-wise). It is equivalent to `np.concatenate((arr1, arr2), axis=0)` for 2D arrays.

### Horizontal Stack (`np.hstack()`)

`np.hstack()` stacks arrays in sequence horizontally (column-wise). It is equivalent to `np.concatenate((arr1, arr2), axis=1)` for 2D arrays.

**Where they are used:**

- **Stacking arrays with matching columns (vstack):** Useful for combining datasets where you have the same features (columns) but different observations (rows).
- **Stacking arrays with matching rows (hstack):** Useful for combining datasets where you have the same observations (rows) but different features (columns).
- **Simplicity:** They offer a simpler syntax than `np.concatenate()` for these common stacking operations.

In [ ]:
import numpy as np

# Create sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.array([[1], [2], [3]])
arr4 = np.array([[4], [5], [6]])

arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([[5, 6], [7, 8]])

# Vertical Stack (vstack)
vstack_1d = np.vstack((arr1, arr2)) # Stacks 1D arrays into a 2D array
print("Vertical stack of 1D arrays:\n", vstack_1d)

vstack_2d = np.vstack((arr5, arr6)) # Stacks 2D arrays vertically
print("\nVertical stack of 2D arrays:\n", vstack_2d)

# Horizontal Stack (hstack)
hstack_1d = np.hstack((arr1, arr2)) # Stacks 1D arrays horizontally into a single 1D array
print("\nHorizontal stack of 1D arrays:", hstack_1d)

hstack_2d = np.hstack((arr5, arr6)) # Stacks 2D arrays horizontally
print("\nHorizontal stack of 2D arrays:\n", hstack_2d)

# Example with arrays that cannot be vstacked (different number of columns)
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6, 7], [8, 9, 10]])

# The following line would raise a ValueError
# vstack_error = np.vstack((arr_a, arr_b))
# print("\nVertical stack with incompatible shapes:\n", vstack_error)

# Example with arrays that cannot be hstacked (different number of rows)
arr_c = np.array([[1, 2, 3]])
arr_d = np.array([[4, 5, 6], [7, 8, 9]])

# The following line would raise a ValueError
# hstack_error = np.hstack((arr_c, arr_d))
# print("\nHorizontal stack with incompatible shapes:\n", hstack_error)

Vertical stack of 1D arrays:
 [[1 2 3]
 [4 5 6]]

Vertical stack of 2D arrays:
 [[1 2 5 6]
 [3 4 7 8]]

Horizontal stack of 1D arrays: [1 2 3 4 5 6]

Horizontal stack of 2D arrays:
 [[1 2 5 6]
 [3 4 7 8]]


## NumPy Stack (`np.stack()`)

The `np.stack()` function in NumPy is used to join a sequence of arrays along a *new* axis. This means it creates a new dimension in the resulting array.

**How it works:**

- It takes a sequence of arrays (e.g., a list or tuple of arrays) as the first argument.
- The `axis` argument specifies the index of the new axis in the dimensions of the result array. For example, if `axis=0`, the new dimension will be the first dimension (like stacking arrays on top of each other).
- All input arrays must have the same shape.

**Where it is used:**

- **Adding a new dimension:** When you want to combine several arrays into a single, higher-dimensional array, such as stacking individual image channels (red, green, blue) into a single image tensor.
- **Batching data:** Creating a batch of data from individual samples for machine learning models.
- **Creating arrays from slices:** Combining several 1D arrays into a 2D array, or several 2D arrays into a 3D array, etc.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Original 1D array 1:", arr1)
print("Original 1D array 2:", arr2)

# Stack along axis 0
stacked_axis_0 = np.stack((arr1, arr2), axis=0)
print("\nStacked along axis 0:\n", stacked_axis_0)
print("Shape (axis=0):", stacked_axis_0.shape)

# Stack along axis 1
stacked_axis_1 = np.stack((arr1, arr2), axis=1)
print("\nStacked along axis 1:\n", stacked_axis_1)
print("Shape (axis=1):", stacked_axis_1.shape)

Original 1D array 1: [1 2 3]
Original 1D array 2: [4 5 6]

Stacked along axis 0:
 [[1 2 3]
 [4 5 6]]
Shape (axis=0): (2, 3)

Stacked along axis 1:
 [[1 4]
 [2 5]
 [3 6]]
Shape (axis=1): (3, 2)


## NumPy Splitting Arrays

NumPy provides several functions to split an array into multiple sub-arrays. These are useful when you need to divide your data for processing, analysis, or to fit certain algorithm inputs.

### `np.split()`

The `np.split()` function splits an array into multiple sub-arrays along a specified axis. You can define either the number of equal divisions or the indices before which the split should occur.

**How it works:**
- `np.split(ary, indices_or_sections, axis=0)`
- `ary`: The array to be split.
- `indices_or_sections`: An integer (N) indicating N equal divisions, or a 1-D array of sorted integers indicating the indices where the array is split.
- `axis`: The axis along which to split (default is 0).

**Where it is used:**
- General-purpose splitting along any axis.
- When you need fine-grained control over where the splits occur.

In [ ]:
import numpy as np

# 1D array splitting
arr_1d = np.arange(1, 11) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Original 1D array:", arr_1d)

# Split into 2 equal parts
split_1d_equal = np.split(arr_1d, 2)
print("\nSplit 1D into 2 equal parts:", split_1d_equal)

# Split at specific indices (before index 3 and before index 7)
split_1d_indices = np.split(arr_1d, [3, 7]) # the first split occurs at 3rd index and the second occurs at 7th index
print("Split 1D at indices [3, 7]:", split_1d_indices)

# 2D array splitting (default axis=0, i.e., rows)
arr_2d = np.arange(1, 17).reshape(4, 4)
print("\nOriginal 2D array:\n", arr_2d)

# Split into 2 equal rows
split_2d_rows_equal = np.split(arr_2d, 2, axis=0) # You can even use Vsplit insted of axis = 0
print("\nSplit 2D into 2 equal row parts (axis=0):\n", split_2d_rows_equal)

# Split at specific row indices
split_2d_row_indices = np.split(arr_2d, [1, 3], axis=0)
print("Split 2D at row indices [1, 3] (axis=0):\n", split_2d_row_indices)

# Split 2D array along columns (axis=1)
# Split into 2 equal columns
split_2d_cols_equal = np.split(arr_2d, 2, axis=1) # You can even use hsplit insted of axis = 1
print("\nSplit 2D into 2 equal column parts (axis=1):\n", split_2d_cols_equal)

# Split at specific column indices
split_2d_col_indices = np.split(arr_2d, [2], axis=1)
print("Split 2D at column index [2] (axis=1):\n", split_2d_col_indices)

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10]

Split 1D into 2 equal parts: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
Split 1D at indices [3, 7]: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Split 2D into 2 equal row parts (axis=0):
 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
Split 2D at row indices [1, 3] (axis=0):
 [array([[1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]

Split 2D into 2 equal column parts (axis=1):
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
Split 2D at column index [2] (axis=1):
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


## `np.repeat()`

The `np.repeat()` function is used to repeat elements of an array. You can specify how many times each element should be repeated and along which axis.

In [ ]:
import numpy as np

arr = np.array([1, 2])

# Repeat each element 3 times
repeated_arr = np.repeat(arr, 3)
print("Repeated array (each element 3 times):", repeated_arr)

arr_2d = np.array([[1, 2], [3, 4]])

# Repeat rows along axis 0
repeated_rows = np.repeat(arr_2d, 2, axis=0)
print("\nRepeated rows (axis=0):\n", repeated_rows)

# Repeat columns along axis 1
repeated_cols = np.repeat(arr_2d, 2, axis=1)
print("\nRepeated columns (axis=1):\n", repeated_cols)

Repeated array (each element 3 times): [1 1 1 2 2 2]

Repeated rows (axis=0):
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]

Repeated columns (axis=1):
 [[1 1 2 2]
 [3 3 4 4]]


## `np.tile()`

The `np.tile()` function is used to construct an array by repeating a given array a specified number of times along each dimension.

In [ ]:
import numpy as np

arr = np.array([1, 2])

# Tile the array 3 times
tiled_arr = np.tile(arr, 3)
print("Tiled array (3 times):", tiled_arr)

arr_2d = np.array([[1, 2], [3, 4]])

# Tile the 2D array:
# Repeat the entire array 2 times horizontally (columns)
# and 1 time vertically (rows)
tiled_2d_horizontal = np.tile(arr_2d, (1, 2))
print("\nTiled 2D array (1x2 repeats):\n", tiled_2d_horizontal)

# Repeat the entire array 2 times vertically (rows)
# and 1 time horizontally (columns)
tiled_2d_vertical = np.tile(arr_2d, (2, 1))
print("\nTiled 2D array (2x1 repeats):\n", tiled_2d_vertical)

# Repeat the entire array 2 times both vertically and horizontally
tiled_2d_both = np.tile(arr_2d, (2, 2))
print("\nTiled 2D array (2x2 repeats):\n", tiled_2d_both)

Tiled array (3 times): [1 2 1 2 1 2]

Tiled 2D array (1x2 repeats):
 [[1 2 1 2]
 [3 4 3 4]]

Tiled 2D array (2x1 repeats):
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]

Tiled 2D array (2x2 repeats):
 [[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
cumsum_1d = np.cumsum(arr_1d)
print("Original 1D array:", arr_1d)
print("Cumulative sum (1D):", cumsum_1d)

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nOriginal 2D array:\n", arr_2d)

# Cumulative sum along default axis (flattened array)
cumsum_2d_flat = np.cumsum(arr_2d)
print("Cumulative sum (flattened):", cumsum_2d_flat)

# Cumulative sum along axis 0 (down columns)
cumsum_2d_axis0 = np.cumsum(arr_2d, axis=0)
print("\nCumulative sum (axis=0 - down columns):\n", cumsum_2d_axis0)

# Cumulative sum along axis 1 (across rows)
cumsum_2d_axis1 = np.cumsum(arr_2d, axis=1)
print("\nCumulative sum (axis=1 - across rows):\n", cumsum_2d_axis1)

## `np.cumsum()` (Cumulative Sum)

The `np.cumsum()` function calculates the cumulative sum of elements along a given axis. It returns an array of the same shape as the input, where each element is the sum of all preceding elements (and itself) along the specified axis.

**How it works:**
- If `axis` is not specified, the array is flattened, and the cumulative sum is computed over the flattened array.
- If `axis` is specified, the cumulative sum is computed independently for each 1D slice along that axis.

**Where it is used:**
- **Prefix sums:** Useful in algorithms where you need to quickly query the sum of elements up to a certain point.
- **Data analysis:** Calculating running totals or financial cumulative sums.
- **Signal processing:** Accumulating values over time.

As you can see from the example, the NumPy vectorized approach is significantly faster than the explicit Python loop, especially for large arrays. This performance gain is why vectorization is a fundamental concept for efficient numerical computing with NumPy.

## `np.cumprod()` (Cumulative Product)

The `np.cumprod()` function calculates the cumulative product of elements along a given axis. It returns an array of the same shape as the input, where each element is the product of all preceding elements (and itself) along the specified axis.

**How it works:**
- Similar to `np.cumsum()`, if `axis` is not specified, the array is flattened.
- If `axis` is specified, the cumulative product is computed independently for each 1D slice along that axis.

**Where it is used:**
- **Compound interest calculations:** Modeling growth or decay over periods.
- **Probability:** Calculating joint probabilities in sequences of events.
- **Combinatorics:** Problems involving permutations or combinations where products are involved.

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
cumprod_1d = np.cumprod(arr_1d)
print("Original 1D array:", arr_1d)
print("Cumulative product (1D):", cumprod_1d)

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nOriginal 2D array:\n", arr_2d)

# Cumulative product along default axis (flattened array)
cumprod_2d_flat = np.cumprod(arr_2d)
print("Cumulative product (flattened):", cumprod_2d_flat)

# Cumulative product along axis 0 (down columns)
cumprod_2d_axis0 = np.cumprod(arr_2d, axis=0)
print("\nCumulative product (axis=0 - down columns):\n", cumprod_2d_axis0)

# Cumulative product along axis 1 (across rows)
cumprod_2d_axis1 = np.cumprod(arr_2d, axis=1)
print("\nCumulative product (axis=1 - across rows):\n", cumprod_2d_axis1)

## `np.where()`

The `np.where()` function is a powerful tool for conditional selection and element replacement in NumPy arrays. It returns elements chosen from `x` or `y` depending on `condition`.

**How it works:**
- `np.where(condition, x, y)`: If `condition` is `True`, `x` is chosen; otherwise, `y` is chosen. `x` and `y` can be scalars or arrays.
- `np.where(condition)`: If only `condition` is provided, it returns the indices where the condition is `True`.

**Where it is used:**
- **Conditional assignment:** Replacing values based on a condition (e.g., setting negative numbers to zero).
- **Filtering data:** Selecting specific elements or sub-arrays that meet certain criteria.
- **Boolean indexing alternative:** Can sometimes be more readable or flexible than direct boolean indexing, especially for element replacement.

In [ ]:
import numpy as np

arr = np.array([1, -2, 3, -4, 5, -6])
print("Original array:", arr)

# Replace negative numbers with 0
result_replace = np.where(arr < 0, 0, arr)
print("Replace negatives with 0:", result_replace)

# Replace numbers greater than 3 with 100, otherwise keep original
result_conditional = np.where(arr > 3, 100, arr)
print("Replace > 3 with 100:", result_conditional)

# Find indices where the condition is True (elements are positive)
indices_positive = np.where(arr > 0)
print("Indices of positive elements:", indices_positive)
print("Elements at positive indices:", arr[indices_positive])

arr_2d = np.array([[1, -5, 3],
                   [0, 8, -2]])
print("\nOriginal 2D array:\n", arr_2d)

# Find indices of elements greater than 0 in a 2D array
indices_2d_gt_0 = np.where(arr_2d > 0)
print("Indices where elements > 0 (row, col tuples):", indices_2d_gt_0)
print("Elements > 0 in 2D array:", arr_2d[indices_2d_gt_0])


## `np.argwhere()`

The `np.argwhere()` function returns the indices of all non-zero elements in the input array, grouped by element. Each row in the output represents the coordinates of a non-zero element.

**How it works:**
- It is similar to `np.where(arr != 0)`, but it always returns an array of (N, arr.ndim) shape, where N is the number of non-zero elements.

**Where it is used:**
- **Finding locations of specific values:** When you need the actual multi-dimensional coordinates of elements that satisfy a condition (e.g., all pixels with a certain color in an image).
- **Sparse data processing:** Identifying the positions of meaningful entries in sparse matrices.
- **Debugging and analysis:** Quickly locating where certain conditions are met in your data.

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([0, 1, 0, 5, 0, 8])
argwhere_1d = np.argwhere(arr_1d)
print("Original 1D array:", arr_1d)
print("Indices of non-zero elements (argwhere 1D):\n", argwhere_1d)

# 2D array
arr_2d = np.array([[0, 1, 0],
                   [2, 0, 3],
                   [0, 4, 0]])
argwhere_2d = np.argwhere(arr_2d)
print("\nOriginal 2D array:\n", arr_2d)
print("Indices of non-zero elements (argwhere 2D):\n", argwhere_2d)

# Using with a boolean condition
condition_arr = np.array([[True, False],
                          [False, True]])
argwhere_condition = np.argwhere(condition_arr)
print("\nBoolean array:\n", condition_arr)
print("Indices where True (argwhere boolean):\n", argwhere_condition)

# Find indices where elements are greater than a value
arr_values = np.array([[10, 20, 5],
                       [30, 0, 15]])
indices_gt_10 = np.argwhere(arr_values > 10)
print("\nOriginal array for values:\n", arr_values)
print("Indices where element > 10:\n", indices_gt_10)

## `np.logical_and()`

The `np.logical_and()` function computes the element-wise logical AND of two (or more) arrays or boolean expressions. It returns a boolean array where `True` indicates that the corresponding elements in both input conditions were `True`.

**How it works:**
- It takes two arguments, `x1` and `x2`, which can be boolean arrays or convertible to booleans.
- `True` AND `True` = `True`
- `True` AND `False` = `False`
- `False` AND `True` = `False`
- `False` AND `False` = `False`

**Where it is used:**
- **Combining multiple conditions:** When you need to filter or select data based on several criteria that must *all* be met simultaneously.
- **Boolean mask creation:** Building complex boolean masks for advanced indexing.
- **Data validation:** Checking if multiple properties are simultaneously true for data points.

In [ ]:
import numpy as np

# Example 1: Combining two boolean arrays
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True, False, False])

result_and_arrays = np.logical_and(arr1, arr2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Logical AND of arrays:", result_and_arrays)

# Example 2: Combining conditions on a numerical array
numbers = np.array([10, 20, 30, 40, 50, 60])
condition1 = (numbers > 20)      # Elements greater than 20
condition2 = (numbers < 50)      # Elements less than 50

result_and_conditions = np.logical_and(condition1, condition2)
print("\nNumbers:", numbers)
print("Condition 1 (numbers > 20):", condition1)
print("Condition 2 (numbers < 50):", condition2)
print("Logical AND of conditions (20 < numbers < 50):", result_and_conditions)
print("Elements satisfying both conditions:", numbers[result_and_conditions])

# Example 3: Logical AND with a scalar
scalar_and_array = np.logical_and(True, arr1)
print("\nLogical AND (True with arr1):", scalar_and_array)

# Example 4: 2D array conditions
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
cond_2d_1 = (arr_2d > 2)
cond_2d_2 = (arr_2d < 8)

result_2d_and = np.logical_and(cond_2d_1, cond_2d_2)
print("\nOriginal 2D array:\n", arr_2d)
print("Condition 1 (arr_2d > 2):\n", cond_2d_1)
print("Condition 2 (arr_2d < 8):\n", cond_2d_2)
print("Logical AND of 2D conditions:\n", result_2d_and)
print("Elements satisfying both 2D conditions:\n", arr_2d[result_2d_and])

## `np.logical_or()`

The `np.logical_or()` function computes the element-wise logical OR of two (or more) arrays or boolean expressions. It returns a boolean array where `True` indicates that at least one of the corresponding elements in the input conditions was `True`.

**How it works:**
- It takes two arguments, `x1` and `x2`, which can be boolean arrays or convertible to booleans.
- `True` OR `True` = `True`
- `True` OR `False` = `True`
- `False` OR `True` = `True`
- `False` OR `False` = `False`

**Where it is used:**
- **Combining multiple conditions:** When you need to filter or select data based on several criteria where *any* of the conditions being met is sufficient.
- **Boolean mask creation:** Building complex boolean masks for advanced indexing, allowing for flexible selection based on multiple possibilities.
- **Data validation:** Checking if at least one of several properties is true for data points.

In [ ]:
import numpy as np

# Example 1: Combining two boolean arrays
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True, False, False])

result_or_arrays = np.logical_or(arr1, arr2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Logical OR of arrays:", result_or_arrays)

# Example 2: Combining conditions on a numerical array
numbers = np.array([10, 20, 30, 40, 50, 60])
condition1 = (numbers < 20)      # Elements less than 20
condition2 = (numbers > 50)      # Elements greater than 50

result_or_conditions = np.logical_or(condition1, condition2)
print("\nNumbers:", numbers)
print("Condition 1 (numbers < 20):", condition1)
print("Condition 2 (numbers > 50):", condition2)
print("Logical OR of conditions (numbers < 20 or numbers > 50):", result_or_conditions)
print("Elements satisfying either condition:", numbers[result_or_conditions])

# Example 3: Logical OR with a scalar
scalar_or_array = np.logical_or(False, arr1)
print("\nLogical OR (False with arr1):", scalar_or_array)

# Example 4: 2D array conditions
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
cond_2d_1 = (arr_2d == 1) # Is element 1
cond_2d_2 = (arr_2d == 9) # Is element 9

result_2d_or = np.logical_or(cond_2d_1, cond_2d_2)
print("\nOriginal 2D array:\n", arr_2d)
print("Condition 1 (arr_2d == 1):\n", cond_2d_1)
print("Condition 2 (arr_2d == 9):\n", cond_2d_2)
print("Logical OR of 2D conditions:\n", result_2d_or)
print("Elements satisfying either 2D condition:\n", arr_2d[result_2d_or])

## `np.nonzero()`

The `np.nonzero()` function in NumPy returns the indices of the elements that are non-zero. It is a powerful tool for quickly finding the positions of specific values or conditions within an array.

**How it works:**
- It takes an array as input.
- It returns a tuple of arrays, one for each dimension of the input array. Each array in the tuple contains the indices of the non-zero elements along that dimension.
- The length of the tuple is equal to the number of dimensions of the input array.

**Where it is used:**
- **Finding specific elements:** Identifying the exact locations (indices) of elements that meet certain criteria (e.g., all positive numbers, all `True` values).
- **Boolean indexing:** Although `np.where()` is often used for this, `np.nonzero()` can provide the indices directly, which can then be used for advanced indexing.
- **Sparse data processing:** Efficiently locating non-zero entries in sparse data structures.
- **Image processing:** Finding the coordinates of pixels with specific values (e.g., non-black pixels).

In [ ]:
import numpy as np

# 1D array example
arr_1d = np.array([0, 1, 0, 5, 0, 8])
nonzero_1d = np.nonzero(arr_1d)
print("Original 1D array:", arr_1d)
print("Index of non-zero elements (1D):", nonzero_1d)
print("Elements at non-zero indices:", arr_1d[nonzero_1d])
# This line fetches the index value from the nonzero_1d and gives the actual value from the arr_1d

# 2D array example
arr_2d = np.array([[0, 1, 0],
                   [2, 0, 3],
                   [0, 4, 0]])
nonzero_2d = np.nonzero(arr_2d)
print("\nOriginal 2D array:\n", arr_2d)
print("Index of non-zero elements (2D):", nonzero_2d)
print("Elements at non-zero indices:\n", arr_2d[nonzero_2d])

# Using with a boolean condition
condition_arr = np.array([[True, False],
                          [False, True]])
nonzero_condition = np.nonzero(condition_arr)
print("\nBoolean array:\n", condition_arr)
print("Index where True (nonzero boolean):", nonzero_condition)

# Find indices where elements are greater than a value
arr_values = np.array([[10, 20, 5],
                       [30, 0, 15]])
indices_gt_10 = np.nonzero(arr_values > 10)
print("\nOriginal array for values:\n", arr_values)
print("Index where element > 10:", indices_gt_10)
print("Elements where element > 10:", arr_values[indices_gt_10])

Original 1D array: [0 1 0 5 0 8]
Index of non-zero elements (1D): (array([1, 3, 5]),)
Elements at non-zero indices: [1 5 8]

Original 2D array:
 [[0 1 0]
 [2 0 3]
 [0 4 0]]
Index of non-zero elements (2D): (array([0, 1, 1, 2]), array([1, 0, 2, 1]))
Elements at non-zero indices:
 [1 2 3 4]

Boolean array:
 [[ True False]
 [False  True]]
Index where True (nonzero boolean): (array([0, 1]), array([0, 1]))

Original array for values:
 [[10 20  5]
 [30  0 15]]
Index where element > 10: (array([0, 1, 1]), array([1, 0, 2]))
Elements where element > 10: [20 30 15]


## NumPy Broadcasting

**Broadcasting** in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It enables you to perform arithmetic operations (like addition, subtraction, multiplication) between arrays that would normally require the arrays to have exactly the same shape.

The core idea is to *virtually* "stretch" the smaller array(s) along the missing or singleton dimensions so that they match the shape of the larger array, without actually making copies of the data. This makes operations very efficient.

### How Broadcasting Works (Rules):

Broadcasting follows a set of rules to determine if two arrays are compatible for an operation:

1.  **Rule 1: Dimensions Comparison:** Start from the trailing (last) dimension and work your way forwards.
2.  **Rule 2: Compatibility Check:** Two dimensions are compatible when:
    *   They are equal, OR
    *   One of them is 1.
3.  **Rule 3: Incompatibility:** If none of these conditions are met, the arrays are not compatible, and a `ValueError` will be raised.

If the dimensions of the two arrays differ, the shape of the one with fewer dimensions is padded with ones on its left side.

### Why it's Useful:

-   **Simplifies Code:** Avoids explicit looping and array repetition, leading to more concise and readable code.
-   **Performance:** Operations are implemented in optimized C code, making them significantly faster than manual Python loops.
-   **Memory Efficiency:** Avoids creating large, redundant copies of data.

In [ ]:
import numpy as np

# Example 1: Scalar-array broadcasting
# A scalar is broadcast across the entire array
arr = np.array([1, 2, 3])
scalar = 5
result_1 = arr + scalar
print("Example 1 (Scalar + Array):\n", result_1)

# Example 2: Broadcasting a 1D array to a 2D array
# The 1D array [10, 20, 30] is broadcast row-wise over the 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_1d = np.array([10, 20, 30])
result_2 = arr_2d + arr_1d
print("\nExample 2 (2D Array + 1D Array - compatible shapes):\n", result_2)

# Example 3: Broadcasting with a column vector
# To broadcast column-wise, the 1D array needs to be reshaped to (rows, 1)
arr_col = np.array([[100],
                    [200],
                    [300]])
result_3 = arr_2d + arr_col
print("\nExample 3 (2D Array + Column Vector - compatible shapes):\n", result_3)

# Example 4: Incompatible shapes (will raise an error)
# Shapes: (3,) and (2,). The trailing dimensions are not compatible (3 vs 2).
# If uncommented, this would cause a ValueError.
# arr_a = np.array([1, 2, 3])
# arr_b = np.array([10, 20])
# result_incompatible = arr_a + arr_b
# print("\nExample 4 (Incompatible shapes - will cause error if uncommented):\n", result_incompatible)

print("\nBroadcasting allows operations between arrays of different shapes when their dimensions are compatible based on specific rules.")

Example 1 (Scalar + Array):
 [6 7 8]

Example 2 (2D Array + 1D Array - compatible shapes):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Example 3 (2D Array + Column Vector - compatible shapes):
 [[101 102 103]
 [204 205 206]
 [307 308 309]]

Broadcasting allows operations between arrays of different shapes when their dimensions are compatible based on specific rules.


## NumPy Vectorization

**Vectorization** in NumPy is the process of replacing explicit Python loops with operations on entire arrays (or vectors) at once. This approach leverages NumPy's optimized C implementations under the hood, leading to significantly faster computations and more concise, readable code.

### Why Vectorization is Important:

1.  **Performance:** Python loops are notoriously slow, especially for large datasets. NumPy's vectorized operations are implemented in C and Fortran, which are much faster than pure Python.
2.  **Readability:** Vectorized code is often more compact and easier to understand than code with explicit loops, as it expresses the intent of the operation directly.
3.  **Memory Efficiency:** While not always the primary goal, vectorized operations can sometimes be more memory-efficient by avoiding the overhead of repeated function calls and object creation within loops.

### How it Works:

NumPy achieves vectorization by applying operations to arrays element-by-element without requiring you to write a loop. This is similar to how mathematical operations work on vectors and matrices.

### Example:

Let's compare a traditional Python loop approach with a vectorized NumPy approach to add two arrays.

In [ ]:
import numpy as np
import time

# Define array size
size = 10000000

# Traditional Python Loop Approach
arr1_python = list(range(size))
arr2_python = list(range(size))
result_python = []

start_time = time.time()
for i in range(size):
    result_python.append(arr1_python[i] + arr2_python[i])
end_time = time.time()
print(f"Python loop time: {end_time - start_time:.4f} seconds")

# NumPy Vectorized Approach
arr1_numpy = np.arange(size)
arr2_numpy = np.arange(size)

start_time = time.time()
result_numpy = arr1_numpy + arr2_numpy
end_time = time.time()
print(f"NumPy vectorized time: {end_time - start_time:.4f} seconds")

print(f"\nFirst 5 elements of Python result: {result_python[:5]}")
print(f"First 5 elements of NumPy result: {result_numpy[:5]}")

Python loop time: 2.5369 seconds
NumPy vectorized time: 0.0439 seconds

First 5 elements of Python result: [0, 2, 4, 6, 8]
First 5 elements of NumPy result: [0 2 4 6 8]


## Handling Missing and Special Values in NumPy

In NumPy, special floating-point values are used to represent undefined results, missing data, or numbers outside the representable range. Understanding and correctly identifying these values is crucial for data cleaning and robust numerical computations.

### Special Values:

-   **`np.nan` (Not a Number):** Represents undefined or unrepresentable numerical results (e.g., `0/0`, `inf - inf`). It's a floating-point type, and its presence in an array will typically cause the array's data type to become `float`.
-   **`np.inf` (Positive Infinity):** Represents a number larger than any finite representable number (e.g., `1/0` for floating-point division).
-   **`-np.inf` (Negative Infinity):** Represents a number smaller than any finite representable number (e.g., `-1/0`).

### Identification Functions:

Since `np.nan` behaves uniquely (e.g., `np.nan == np.nan` is `False`), direct comparison cannot be used to check for these special values. NumPy provides dedicated functions:

-   **`np.isnan(array)`:** Returns a boolean array (`True` where elements are `np.nan`, `False` otherwise).
-   **`np.isinf(array)`:** Returns a boolean array (`True` where elements are `np.inf` or `-np.inf`, `False` otherwise).
-   **`np.isfinite(array)`:** Returns a boolean array (`True` where elements are *not* `np.nan`, `np.inf`, or `-np.inf`; i.e., they are finite numbers).

### Handling Strategies:

Once identified, these special values can be handled by:

-   **Filtering:** Removing rows or elements that contain these values.
-   **Imputation:** Replacing them with a substitute (e.g., mean, median, zero, a specific constant).
-   **Transformation:** Using functions like `np.nan_to_num()` to convert `nan` or `inf` to a finite number.

In [ ]:
import numpy as np

# Create a sample array with various special values
arr = np.array([1.0, 2.5, np.nan, 4.0, np.inf, -np.inf, 7.0, 0.0, -99.9])
print("Original Array:", arr)
print("Array Dtype:", arr.dtype)

# --- 1. Identifying Special Values ---

# Check for NaN (Not a Number)
is_nan_mask = np.isnan(arr)
print("\nIs NaN Mask:", is_nan_mask)
print("NaN values found at indices:", np.where(is_nan_mask)[0])
print("Corresponding NaN values:", arr[is_nan_mask])

# Check for Infinity (positive or negative)
is_inf_mask = np.isinf(arr)
print("\nIs Inf Mask:", is_inf_mask)
print("Infinite values found at indices:", np.where(is_inf_mask)[0])
print("Corresponding Infinite values:", arr[is_inf_mask])

# Check for Finite numbers (not NaN, not Inf)
is_finite_mask = np.isfinite(arr)
print("\nIs Finite Mask:", is_finite_mask)
print("Finite values found at indices:", np.where(is_finite_mask)[0])
print("Corresponding Finite values:", arr[is_finite_mask])

# --- 2. Handling Strategies ---

# Strategy A: Filtering/Removing special values
filtered_arr = arr[np.isfinite(arr)]
print("\nArray after filtering out NaN and Inf:", filtered_arr)

# Strategy B: Imputing NaN values
# Example: Replace NaN with the mean of finite values
mean_of_finite = np.nanmean(arr) # nanmean ignores NaN values for calculation
print("Mean of finite values:", mean_of_finite)

# Create a copy to avoid modifying original array directly for demonstration
imputed_arr_mean = np.copy(arr)
imputed_arr_mean[is_nan_mask] = mean_of_finite
print("Array after imputing NaN with mean:", imputed_arr_mean)

# Strategy C: Replacing special values with specific numbers using np.nan_to_num
# This function converts NaN to 0, positive infinity to a very large number,
# and negative infinity to a very small (large negative) number by default.
converted_arr = np.nan_to_num(arr)
print("\nArray after converting NaN to 0 and Inf to large numbers:", converted_arr)

# You can also specify custom replacement values
custom_converted_arr = np.nan_to_num(arr, nan=-1.0, posinf=1000.0, neginf=-1000.0)
print("Array with custom replacements for NaN and Inf:", custom_converted_arr)

# --- Example with a 2D Array ---

arr_2d = np.array([ [1, np.nan, 3],
                    [np.inf, 5, -np.inf],
                    [7, 8, np.nan] ])
print("\nOriginal 2D Array:\n", arr_2d)

# Find indices of all special values in 2D array
nan_indices_2d = np.where(np.isnan(arr_2d))
inf_indices_2d = np.where(np.isinf(arr_2d))

print("\nNaN indices in 2D (rows, cols):", nan_indices_2d)
print("Inf indices in 2D (rows, cols):", inf_indices_2d)

# Replace all special values in 2D array with 0
cleaned_2d_arr = np.nan_to_num(arr_2d, nan=0.0, posinf=0.0, neginf=0.0)
print("\n2D Array after replacing all special values with 0:\n", cleaned_2d_arr)